// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddTodo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"h-dvh grid place-items-center p-5 bg-stone-50\" x-data=\"{ shown: false }\" x-intersect=\"shown = true\"><div class=\"lg:w-1/2 shadow-lg\" x-show=\"shown\" x-transition.duration.1000ms x-cloak><form class=\"flex flex-col p-5 rounded\" action=\"/add\" method=\"POST\"><h1 class=\"text-2xl capitalize font-black mb-2\">add new item</h1><label for=\"item\" class=\"capitalize mb-2 text-stone-500\">Example: banana...</label> <input class=\"bg-stone-200 mb-4 pl-2 py-2\" type=\"text\" id=\"item\" name=\"name\"> <button type=\"submit\" class=\"text-stone-50 capitalize py-2 px-4 cursor-pointer bg-go hover:bg-green-500 transition-all duration-300\">add</button></form></div><a href=\"/\" class=\"capitalize\">back</a></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
